Algoritmo "Questão 03"
//Fazer um programa que pergunte um valor em Dólares e
//apresente o equivalente em Reais.
//Considere U$1,00 = R$1,72.

Var
// Seção de Declarações das variáveis 
 dolar: real
 reais : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva (" Informe um valor em dólares:")
 leia ( dolar )
 
 reais <- 1.72
 escreva ( "Esse é o valor convertido em reais: " , dolar * reais )

 
 


Fimalgoritmo